export const USER_ID_CHANGE = 'USER_ID_CHANGE'
export const USER_NAME_CHANGE = 'USER_NAME_CHANGE'
export const USER_LOGGED_CHANGE = 'USER_LOGGED_CHANGE'
export const USER_DETAILS = 'USER_DETAILS'

export const INCREMENT="INCREMENT";
export const DECREMENT="DECREMENT";
export const CUSTOM_VALUE_INCREMENT="CUSTOM_VALUE_INCREMENT";
export const CUSTOM_VALUE_DECREMENT="CUSTOM_VALUE_DECREMENT";
export const CUSTOM_VALUE="CUSTOM_VALUE"; 